services:
  - type: web
    name: task-manager-backend
    env: node
    region: singapore # You can change this to your preferred region
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false # This will be set manually in Render dashboard for security
      - key: JWT_SECRET
        sync: false # This will be set manually in Render dashboard for security
    autoDeploy: true
    plan: starter # You can change this based on your needs
    scaling:
      minInstances: 1
      maxInstances: 1
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
    routes:
      - type: rewrite
        source: /*
        destination: /