services:
  - type: web
    name: task-manager-backend
    env: node
    region: singapore
    buildCommand: npm ci --only=production && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    autoDeploy: true
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 2
      targetCPUPercent: 70
